### ISSUE TITLE
EPiFind (400) Bad Request: "ScriptException[dynamic scripting disabled]"

### ISSUE THREAD

**Issue by AndrewSaninCreuna** [x2find/Random2Find#1]
Hi Henrik

We were successfully using your library on one of our projects, but unfortunately starting from the middle of previous week it started to fail, but only with EPiServer Find developer indexes.

You are using custom script "random()" to sort. And on our dev sites we started to see crashes because of Find "400 Bad Request" error: `nested: ScriptException[dynamic scripting disabled]`. 

Production sites work fine, so looks like the issue is only related to development Find indexes.

Do you know about this issue? We would appreciate any ideas or hints on how to fix this.
EPiserver Dev support refuses to help because it's a custom 3rd party library that they don't support.

Full response from Find + stack:

```
System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerWrapper'. ---> System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> EPiServer.Find.ServiceException: The remote server returned an error: (400) Bad Request.
SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[v78fyBJHT1mcXhXpbsNGuA][andrew.sanin_foodservicestaging][4]: RemoteTransportException[[sefinddev02esd02][inet[/10.3.98.42:9300]][search/phase/query]]; nested: SearchParseException[[andrew.sanin_foodservicestaging][4]: query[filtered(ConstantScore(+cache(MarkAsNewIndicator.StartDate$$date:[-62135596800000 TO 1424818800001}) +cache(MarkAsNewIndicatorFinishDate$$date:{1424818800001 TO 253402297199999]) +cache(Pictures.Position$$number:[0.0 TO 0.0])))->cache(___types:Website.Data.Content.RecipeExtended)],from[0],size[2]: Parse Failure [Failed to parse source [{"from":0,"size":2,"query":{"filtered":{"query":{"constant_score":{"filter":{"and":[{"range":{"MarkAsNewIndicator.StartDate$$date":{"from":"0001-01-01T00:00:00Z","to":"2015-02-24T23:00:00.001Z","include_lower":true,"include_upper":false}}},{"range":{"MarkAsNewIndicatorFinishDate$$date":{"from":"2015-02-24T23:00:00.001Z","to":"9999-12-31T22:59:59.9999999Z","include_lower":false,"include_upper":true}}},{"term":{"Pictures.Position$$number":0}}]}}},"filter":{"term":{"___types":"Website.Data.Content.RecipeExtended"}}}},"sort":[{"_script":{"script":"random()","type":"number"}}]}]]]; nested: ScriptException[dynamic scripting disabled]; }{[kFCpSJHyRtGXEM9YhH4m4A][andrew.sanin_foodservicestaging][3]: SearchParseException[[andrew.sanin_foodservicestaging][3]: query[filtered(ConstantScore(+cache(MarkAsNewIndicator.StartDate$$date:[-62135596800000 TO 1424818800001}) +cache(MarkAsNewIndicatorFinishDate$$date:{1424818800001 TO 253402297199999]) +cache(Pictures.Position$$number:[0.0 TO 0.0])))->cache(___types:Website.Data.Content.RecipeExtended)],from[0],size[2]: Parse Failure [Failed to parse source [{"from":0,"size":2,"query":{"filtered":{"query":{"constant_score":{"filter":{"and":[{"range":{"MarkAsNewIndicator.StartDate$$date":{"from":"0001-01-01T00:00:00Z","to":"2015-02-24T23:00:00.001Z","include_lower":true,"include_upper":false}}},{"range":{"MarkAsNewIndicatorFinishDate$$date":{"from":"2015-02-24T23:00:00.001Z","to":"9999-12-31T22:59:59.9999999Z","include_lower":false,"include_upper":true}}},{"term":{"Pictures.Position$$number":0}}]}}},"filter":{"term":{"___types":"Website.Data.Content.RecipeExtended"}}}},"sort":[{"_script":{"script":"random()","type":"number"}}]}]]]; nested: ScriptException[dynamic scripting disabled]; }{[v78fyBJHT1mcXhXpbsNGuA][andrew.sanin_foodservicestaging][2]: RemoteTransportException[[sefinddev02esd02][inet[/10.3.98.42:9300]][search/phase/query]]; nested: SearchParseException[[andrew.sanin_foodservicestaging][2]: query[filtered(ConstantScore(+cache(MarkAsNewIndicator.StartDate$$date:[-62135596800000 TO 1424818800001}) +cache(MarkAsNewIndicatorFinishDate$$date:{1424818800001 TO 253402297199999]) +cache(Pictures.Position$$number:[0.0 TO 0.0])))->cache(___types:Website.Data.Content.RecipeExtended)],from[0],size[2]: Parse Failure [Failed to parse source [{"from":0,"size":2,"query":{"filtered":{"query":{"constant_score":{"filter":{"and":[{"range":{"MarkAsNewIndicator.StartDate$$date":{"from":"0001-01-01T00:00:00Z","to":"2015-02-24T23:00:00.001Z","include_lower":true,"include_upper":false}}},{"range":{"MarkAsNewIndicatorFinishDate$$date":{"from":"2015-02-24T23:00:00.001Z","to":"9999-12-31T22:59:59.9999999Z","include_lower":false,"include_upper":true}}},{"term":{"Pictures.Position$$number":0}}]}}},"filter":{"term":{"___types":"Website.Data.Content.RecipeExtended"}}}},"sort":[{"_script":{"script":"random()","type":"number"}}]}]]]; nested: ScriptException[dynamic scripting disabled]; }{[kFCpSJHyRtGXEM9YhH4m4A][andrew.sanin_foodservicestaging][1]: SearchParseException[[andrew.sanin_foodservicestaging][1]: query[filtered(ConstantScore(+cache(MarkAsNewIndicator.StartDate$$date:[-62135596800000 TO 1424818800001}) +cache(MarkAsNewIndicatorFinishDate$$date:{1424818800001 TO 253402297199999]) +cache(Pictures.Position$$number:[0.0 TO 0.0])))->cache(___types:Website.Data.Content.RecipeExtended)],from[0],size[2]: Parse Failure [Failed to parse source [{"from":0,"size":2,"query":{"filtered":{"query":{"constant_score":{"filter":{"and":[{"range":{"MarkAsNewIndicator.StartDate$$date":{"from":"0001-01-01T00:00:00Z","to":"2015-02-24T23:00:00.001Z","include_lower":true,"include_upper":false}}},{"range":{"MarkAsNewIndicatorFinishDate$$date":{"from":"2015-02-24T23:00:00.001Z","to":"9999-12-31T22:59:59.9999999Z","include_lower":false,"include_upper":true}}},{"term":{"Pictures.Position$$number":0}}]}}},"filter":{"term":{"___types":"Website.Data.Content.RecipeExtended"}}}},"sort":[{"_script":{"script":"random()","type":"number"}}]}]]]; nested: ScriptException[dynamic scripting disabled]; }{[v78fyBJHT1mcXhXpbsNGuA][andrew.sanin_foodservicestaging][0]: RemoteTransportException[[sefinddev02esd02][inet[/10.3.98.42:9300]][search/phase/query]]; nested: SearchParseException[[andrew.sanin_foodservicestaging][0]: query[filtered(ConstantScore(+cache(MarkAsNewIndicator.StartDate$$date:[-62135596800000 TO 1424818800001}) +cache(MarkAsNewIndicatorFinishDate$$date:{1424818800001 TO 253402297199999]) +cache(Pictures.Position$$number:[0.0 TO 0.0])))->cache(___types:Website.Data.Content.RecipeExtended)],from[0],size[2]: Parse Failure [Failed to parse source [{"from":0,"size":2,"query":{"filtered":{"query":{"constant_score":{"filter":{"and":[{"range":{"MarkAsNewIndicator.StartDate$$date":{"from":"0001-01-01T00:00:00Z","to":"2015-02-24T23:00:00.001Z","include_lower":true,"include_upper":false}}},{"range":{"MarkAsNewIndicatorFinishDate$$date":{"from":"2015-02-24T23:00:00.001Z","to":"9999-12-31T22:59:59.9999999Z","include_lower":false,"include_upper":true}}},{"term":{"Pictures.Position$$number":0}}]}}},"filter":{"term":{"___types":"Website.Data.Content.RecipeExtended"}}}},"sort":[{"_script":{"script":"random()","type":"number"}}]}]]]; nested: ScriptException[dynamic scripting disabled]; }] ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
at System.Net.HttpWebRequest.GetResponse()
at EPiServer.Find.Connection.JsonRequest.GetResponse()
at EPiServer.Find.Api.Command.GetResponse[TResult](IJsonRequest request)
--- End of inner exception stack trace ---
at EPiServer.Find.Api.Command.GetResponse[TResult](IJsonRequest request)
at EPiServer.Find.Api.SearchCommand`1.Execute()
at EPiServer.Find.Client.Search[TResult](SearchRequestBody requestBody, Action`1 commandAction)
at EPiServer.Find.SearchExtensions.GetResult[TResult](ISearch`1 search)
at Website.Business.Search.FindRepository`1.GetSearchResult(Func`2 filter, Int32 skip, Int32 take, Nullable`1 cacheFor) in c:\TeamCity\buildAgent\work\2e7fb52a4f8d0d13\Website\Business\Search\FindRepository.cs:line 40
at Website.Business.Search.FindRepository`1.Search(Func`2 filter, Int32 skip, Int32 take, Nullable`1 cacheFor) in c:\TeamCity\buildAgent\work\2e7fb52a4f8d0d13\Website\Business\Search\FindRepository.cs:line 34
at Website.Business.Search.RecipeRepository.GetRandomNewRecipes(IEnumerable`1 excludeRecipeIds, Int32 take) in c:\TeamCity\buildAgent\work\2e7fb52a4f8d0d13\Website\Business\Search\RecipeRepository.cs:line 82
at Website.Business.Search.RecipeRepository.GetRandomNewOrOtherRecipes(IEnumerable`1 excludeRecipeIds, Int32 take) in c:\TeamCity\buildAgent\work\2e7fb52a4f8d0d13\Website\Business\Search\RecipeRepository.cs:line 69
at Website.Controllers.Blocks.NewRecipesBlockController.Index(NewRecipesBlock currentBlock) in c:\TeamCity\buildAgent\work\2e7fb52a4f8d0d13\Website\Controllers\Blocks\NewRecipesBlockController.cs:line 30
```

Thanks in advance for any help.

**Comment by lindstromhenrik** [comment]
Hi

As of EPiServer.Find 9 custom scripting is disabled. I've updated master to use a native script counterpart for the random()-script previously used when sorting.

/Henrik

**Comment by AndrewSaninCreuna** [comment]
@lindstromhenrik Thanks a lot for your quick reply and fix. Could you also update Nuget package?

**Comment by lindstromhenrik** [comment]
Yes, I've uploaded an updated nuget package (version 1.1.0.0). It will be available shortly.

**Comment by AndrewSaninCreuna** [comment]
:+1: It's very appreciated. Thanks.

**Comment by rbaarda** [comment]
We are having the same problem and are using EPiServer Find 7. We have recently created a new developer index for a site we've build and all of a sudden this exception popped up.
We were wondering, how version independent is a Find Index? The production index seems fine but if we ever create a new production index (for whatever reason) then will the same problem occur?
If we upgrade to EPiServer Find 9 and apply your updated source, will that function on the production index? So in other words, how backwards compatible is this?
PS: The site is running EPiServer 7.

**Comment by lindstromhenrik** [comment]
The Find index is version independent and you should update to this never version (it is backwards compatible with all your 'old' indices).
